
package artifactnew;

import java.math.BigDecimal;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "project_2_webnew", targetNamespace = "http://project_2_webnew/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Project2Webnew {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(operationName = "artists_names")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "artists_names", targetNamespace = "http://project_2_webnew/", className = "artifactnew.ArtistsNames")
    @ResponseWrapper(localName = "artists_namesResponse", targetNamespace = "http://project_2_webnew/", className = "artifactnew.ArtistsNamesResponse")
    public List<String> artistsNames(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(operationName = "album_title")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "album_title", targetNamespace = "http://project_2_webnew/", className = "artifactnew.AlbumTitle")
    @ResponseWrapper(localName = "album_titleResponse", targetNamespace = "http://project_2_webnew/", className = "artifactnew.AlbumTitleResponse")
    public List<String> albumTitle(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(operationName = "alb_gen_lab")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "alb_gen_lab", targetNamespace = "http://project_2_webnew/", className = "artifactnew.AlbGenLab")
    @ResponseWrapper(localName = "alb_gen_labResponse", targetNamespace = "http://project_2_webnew/", className = "artifactnew.AlbGenLabResponse")
    public int albGenLab(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<String> arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<artifactnew.Vinyl>
     */
    @WebMethod(operationName = "albums_genre_score")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "albums_genre_score", targetNamespace = "http://project_2_webnew/", className = "artifactnew.AlbumsGenreScore")
    @ResponseWrapper(localName = "albums_genre_scoreResponse", targetNamespace = "http://project_2_webnew/", className = "artifactnew.AlbumsGenreScoreResponse")
    public List<Vinyl> albumsGenreScore(
        @WebParam(name = "arg0", targetNamespace = "")
        BigDecimal arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod(operationName = "average_score")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "average_score", targetNamespace = "http://project_2_webnew/", className = "artifactnew.AverageScore")
    @ResponseWrapper(localName = "average_scoreResponse", targetNamespace = "http://project_2_webnew/", className = "artifactnew.AverageScoreResponse")
    public float averageScore(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<artifactnew.Vinyl>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "albumsGenre", targetNamespace = "http://project_2_webnew/", className = "artifactnew.AlbumsGenre")
    @ResponseWrapper(localName = "albumsGenreResponse", targetNamespace = "http://project_2_webnew/", className = "artifactnew.AlbumsGenreResponse")
    public List<Vinyl> albumsGenre(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0);

    /**
     * 
     * @return
     *     returns java.util.List<artifactnew.Vinyl>
     */
    @WebMethod(operationName = "total_vinyls")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "total_vinyls", targetNamespace = "http://project_2_webnew/", className = "artifactnew.TotalVinyls")
    @ResponseWrapper(localName = "total_vinylsResponse", targetNamespace = "http://project_2_webnew/", className = "artifactnew.TotalVinylsResponse")
    public List<Vinyl> totalVinyls();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<artifactnew.Vinyl>
     */
    @WebMethod(operationName = "album_score")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "album_score", targetNamespace = "http://project_2_webnew/", className = "artifactnew.AlbumScore")
    @ResponseWrapper(localName = "album_scoreResponse", targetNamespace = "http://project_2_webnew/", className = "artifactnew.AlbumScoreResponse")
    public List<Vinyl> albumScore(
        @WebParam(name = "arg0", targetNamespace = "")
        BigDecimal arg0);

}
