
package artifactnew;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "project_2_webnewService", targetNamespace = "http://project_2_webnew/", wsdlLocation = "http://localhost:8080/project_2_webnew/project_2_webnew?wsdl")
public class Project2WebnewService
    extends Service
{

    private final static URL PROJECT2WEBNEWSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROJECT2WEBNEWSERVICE_EXCEPTION;
    private final static QName PROJECT2WEBNEWSERVICE_QNAME = new QName("http://project_2_webnew/", "project_2_webnewService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/project_2_webnew/project_2_webnew?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROJECT2WEBNEWSERVICE_WSDL_LOCATION = url;
        PROJECT2WEBNEWSERVICE_EXCEPTION = e;
    }

    public Project2WebnewService() {
        super(__getWsdlLocation(), PROJECT2WEBNEWSERVICE_QNAME);
    }

    public Project2WebnewService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROJECT2WEBNEWSERVICE_QNAME, features);
    }

    public Project2WebnewService(URL wsdlLocation) {
        super(wsdlLocation, PROJECT2WEBNEWSERVICE_QNAME);
    }

    public Project2WebnewService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROJECT2WEBNEWSERVICE_QNAME, features);
    }

    public Project2WebnewService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Project2WebnewService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Project2Webnew
     */
    @WebEndpoint(name = "project_2_webnewPort")
    public Project2Webnew getProject2WebnewPort() {
        return super.getPort(new QName("http://project_2_webnew/", "project_2_webnewPort"), Project2Webnew.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Project2Webnew
     */
    @WebEndpoint(name = "project_2_webnewPort")
    public Project2Webnew getProject2WebnewPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://project_2_webnew/", "project_2_webnewPort"), Project2Webnew.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROJECT2WEBNEWSERVICE_EXCEPTION!= null) {
            throw PROJECT2WEBNEWSERVICE_EXCEPTION;
        }
        return PROJECT2WEBNEWSERVICE_WSDL_LOCATION;
    }

}
