//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.03.06 at 05:52:07 PM GMT 
//

package music;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}category" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{}statistics"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "category", "statistics" })
@XmlRootElement(name = "catalognew")
public class Catalognew {

	@XmlElement(required = true)
	protected List<Category> category;
	@XmlElement(required = true)
	protected Statistics statistics;

	/**
	 * Gets the value of the category property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the category property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCategory().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Category }
	 * 
	 * 
	 */
	public List<Category> getCategory() {
		if (category == null) {
			category = new ArrayList<Category>();
		}
		return this.category;
	}

	public void setCategory(List<Category> category) {
		this.category = category;
	}

	/**
	 * Gets the value of the statistics property.
	 * 
	 * @return possible object is {@link Statistics }
	 * 
	 */
	public Statistics getStatistics() {
		return statistics;
	}

	/**
	 * Sets the value of the statistics property.
	 * 
	 * @param value
	 *            allowed object is {@link Statistics }
	 * 
	 */
	public void setStatistics(Statistics value) {
		this.statistics = value;
	}

}
