//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.03.01 at 04:35:37 PM GMT 
//


package music;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}artistname"/&gt;
 *         &lt;element ref="{}artistalbum"/&gt;
 *         &lt;element ref="{}numberscore"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "artistname",
    "artistalbum",
    "numberscore"
})
@XmlRootElement(name = "rateartists")
public class Rateartists {

    @XmlElement(required = true)
    protected String artistname;
    @XmlElement(required = true)
    protected String artistalbum;
    @XmlElement(required = true)
    protected BigDecimal numberscore;

    /**
     * Gets the value of the artistname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtistname() {
        return artistname;
    }

    /**
     * Sets the value of the artistname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtistname(String value) {
        this.artistname = value;
    }

    /**
     * Gets the value of the artistalbum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtistalbum() {
        return artistalbum;
    }

    /**
     * Sets the value of the artistalbum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtistalbum(String value) {
        this.artistalbum = value;
    }

    /**
     * Gets the value of the numberscore property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNumberscore() {
        return numberscore;
    }

    /**
     * Sets the value of the numberscore property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNumberscore(BigDecimal value) {
        this.numberscore = value;
    }

}
