//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.03.01 at 04:35:37 PM GMT 
//


package music;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}totalartists" minOccurs="0"/&gt;
 *         &lt;element ref="{}rateartists" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "totalartists",
    "rateartists"
})
@XmlRootElement(name = "statistics")
public class Statistics {

    protected BigInteger totalartists;
    protected List<Rateartists> rateartists;

    public void setRateartists(List<Rateartists> rateartists) {
		this.rateartists = rateartists;
	}

	/**
     * Gets the value of the totalartists property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalartists() {
        return totalartists;
    }

    /**
     * Sets the value of the totalartists property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalartists(BigInteger value) {
        this.totalartists = value;
    }

    /**
     * Gets the value of the rateartists property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rateartists property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRateartists().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Rateartists }
     * 
     * 
     */
    public List<Rateartists> getRateartists() {
        if (rateartists == null) {
            rateartists = new ArrayList<Rateartists>();
        }
        return this.rateartists;
    }

}
