
package artifact;

import java.math.BigDecimal;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "projeto_2_ws", targetNamespace = "http://projeto_2_web/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Projeto2Ws {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<artifact.Vinyl>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "scoresabovex", targetNamespace = "http://projeto_2_web/", className = "artifact.Scoresabovex")
    @ResponseWrapper(localName = "scoresabovexResponse", targetNamespace = "http://projeto_2_web/", className = "artifact.ScoresabovexResponse")
    public List<Vinyl> scoresabovex(
        @WebParam(name = "arg0", targetNamespace = "")
        BigDecimal arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "titles", targetNamespace = "http://projeto_2_web/", className = "artifact.Titles")
    @ResponseWrapper(localName = "titlesResponse", targetNamespace = "http://projeto_2_web/", className = "artifact.TitlesResponse")
    public List<String> titles();

    /**
     * 
     * @return
     *     returns java.util.List<artifact.Vinyl>
     */
    @WebMethod(operationName = "total_data")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "total_data", targetNamespace = "http://projeto_2_web/", className = "artifact.TotalData")
    @ResponseWrapper(localName = "total_dataResponse", targetNamespace = "http://projeto_2_web/", className = "artifact.TotalDataResponse")
    public List<Vinyl> totalData();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "artists", targetNamespace = "http://projeto_2_web/", className = "artifact.Artists")
    @ResponseWrapper(localName = "artistsResponse", targetNamespace = "http://projeto_2_web/", className = "artifact.ArtistsResponse")
    public List<String> artists();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<artifact.Vinyl>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "albumBygenre", targetNamespace = "http://projeto_2_web/", className = "artifact.AlbumBygenre")
    @ResponseWrapper(localName = "albumBygenreResponse", targetNamespace = "http://projeto_2_web/", className = "artifact.AlbumBygenreResponse")
    public List<Vinyl> albumBygenre(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<artifact.Vinyl>
     */
    @WebMethod(operationName = "album_getinfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "album_getinfo", targetNamespace = "http://projeto_2_web/", className = "artifact.AlbumGetinfo")
    @ResponseWrapper(localName = "album_getinfoResponse", targetNamespace = "http://projeto_2_web/", className = "artifact.AlbumGetinfoResponse")
    public List<Vinyl> albumGetinfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
