
package artifact;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "projeto_2_wsService", targetNamespace = "http://projeto_2_web/", wsdlLocation = "http://localhost:8080/projeto_2_web/projeto_2_ws?wsdl")
public class Projeto2WsService
    extends Service
{

    private final static URL PROJETO2WSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROJETO2WSSERVICE_EXCEPTION;
    private final static QName PROJETO2WSSERVICE_QNAME = new QName("http://projeto_2_web/", "projeto_2_wsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/projeto_2_web/projeto_2_ws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROJETO2WSSERVICE_WSDL_LOCATION = url;
        PROJETO2WSSERVICE_EXCEPTION = e;
    }

    public Projeto2WsService() {
        super(__getWsdlLocation(), PROJETO2WSSERVICE_QNAME);
    }

    public Projeto2WsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROJETO2WSSERVICE_QNAME, features);
    }

    public Projeto2WsService(URL wsdlLocation) {
        super(wsdlLocation, PROJETO2WSSERVICE_QNAME);
    }

    public Projeto2WsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROJETO2WSSERVICE_QNAME, features);
    }

    public Projeto2WsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Projeto2WsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Projeto2Ws
     */
    @WebEndpoint(name = "projeto_2_wsPort")
    public Projeto2Ws getProjeto2WsPort() {
        return super.getPort(new QName("http://projeto_2_web/", "projeto_2_wsPort"), Projeto2Ws.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Projeto2Ws
     */
    @WebEndpoint(name = "projeto_2_wsPort")
    public Projeto2Ws getProjeto2WsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://projeto_2_web/", "projeto_2_wsPort"), Projeto2Ws.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROJETO2WSSERVICE_EXCEPTION!= null) {
            throw PROJETO2WSSERVICE_EXCEPTION;
        }
        return PROJETO2WSSERVICE_WSDL_LOCATION;
    }

}
