//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.19 at 04:26:14 PM GMT 
//

package classes_xml;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}title"/&gt;
 *         &lt;element ref="{}artist" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{}year"/&gt;
 *         &lt;element ref="{}genre" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{}rating" minOccurs="0"/&gt;
 *         &lt;element ref="{}nreview" minOccurs="0"/&gt;
 *         &lt;element ref="{}music" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{}price"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "title", "artist", "year", "genre", "rating", "nreview", "music", "price", "label" })
@XmlRootElement(name = "vinyl")
@Entity
public class Vinyl implements Serializable {
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public void setArtist(List<String> artist) {
		this.artist = artist;
	}

	public void setGenre(List<String> genre) {
		this.genre = genre;
	}

	public void setMusic(List<Music> music) {
		this.music = music;
	}

	private static final long serialVersionUID = 1L;
	@XmlElement(required = true)
	protected String title;
	@XmlElement(required = true)
	@ElementCollection
	@CollectionTable
	protected List<String> artist;;
	@XmlElement(required = true)
	protected BigInteger year;
	@XmlElement(required = true)
	@ElementCollection
	@CollectionTable
	protected List<String> genre;
	protected BigDecimal rating;
	protected BigInteger nreview;
	@XmlElement(required = true)
	@OneToMany
	protected List<Music> music;
	@XmlElement(required = true)
	protected BigDecimal price;
	@XmlElement(required = true)
	protected String label;
	@XmlAttribute(name = "id", required = true)
	@Id
	@Column(name = "ASIN")
	protected String id;

	/**
	 * Gets the value of the title property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * Sets the value of the title property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTitle(String value) {
		this.title = value;
	}

	public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	/**
	 * Gets the value of the artist property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the artist property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getArtist().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getArtist() {
		if (artist == null) {
			artist = new ArrayList<String>();
		}
		return this.artist;
	}

	/**
	 * Gets the value of the asin property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */

	/**
	 * Gets the value of the year property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getYear() {
		return year;
	}

	/**
	 * Sets the value of the year property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setYear(BigInteger value) {
		this.year = value;
	}

	/**
	 * Gets the value of the genre property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the genre property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getGenre().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getGenre() {
		if (genre == null) {
			genre = new ArrayList<String>();
		}
		return this.genre;
	}

	/**
	 * Gets the value of the rating property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getRating() {
		return rating;
	}

	/**
	 * Sets the value of the rating property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 * 
	 */
	public void setRating(BigDecimal value) {
		this.rating = value;
	}

	/**
	 * Gets the value of the nreview property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getNreview() {
		return nreview;
	}

	/**
	 * Sets the value of the nreview property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setNreview(BigInteger value) {
		this.nreview = value;
	}

	/**
	 * Gets the value of the music property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the music property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getMusic().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Music }
	 * 
	 * 
	 */
	public List<Music> getMusic() {
		if (music == null) {
			music = new ArrayList<Music>();
		}
		return this.music;
	}

	/**
	 * Gets the value of the price property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * Sets the value of the price property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 * 
	 */
	public void setPrice(BigDecimal value) {
		this.price = value;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setId(String value) {
		this.id = value;
	}

}
